version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${PS_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes: 
      - cache:/data

  backend:
    build: ./ads-backend
    image: ads-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_URL: redis://redis:6379/1
      REDIS_PORT: 6379
      DATABASE_URL: postgres://postgres:${PS_PASSWORD}@db:5432/ads_backend_development

  frontend:
    build: ./advertisement-site
    image: ads-frontend
    ports:
      - "3001:3001"
    environment:
      - HOST=0.0.0.0

volumes:
  dbdata:
  cache:
